export const GET_PRODUCTS = 'GET_PRODUCTS'; 
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const CATEGORY_FILTER = 'CATEGORY_FILTER';
export const ALL_CATEGORIES = 'ALL_CATEGORIES';
export const ADD_TO_CHART = 'ADD_TO_CHART';
export const REMOVE_FROM_CHART = 'REMOVE_FROM_CHART';


