export const GET_PRODUCTS = "GET_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const CATEGORY_FILTER = "CATEGORY_FILTER";
export const ALL_CATEGORIES = "ALL_CATEGORIES";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART = "UPDATE_CART";
export const PAY_MERCADOPAGO = "PAY_MERCADOPAGO";
export const CLEAR_DETAIL = "CLEAR_DETAIL";
export const COLLECT_USERNAME = "COLLECT_USERNAME";

